// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// UploadStatusAction is an autogenerated mock type for the UploadStatusAction type
type UploadStatusAction struct {
	mock.Mock
}

type UploadStatusAction_Expecter struct {
	mock *mock.Mock
}

func (_m *UploadStatusAction) EXPECT() *UploadStatusAction_Expecter {
	return &UploadStatusAction_Expecter{mock: &_m.Mock}
}

// Invoke provides a mock function with given fields: context
func (_m *UploadStatusAction) Invoke(context *gin.Context) {
	_m.Called(context)
}

// UploadStatusAction_Invoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Invoke'
type UploadStatusAction_Invoke_Call struct {
	*mock.Call
}

// Invoke is a helper method to define mock.On call
//   - context *gin.Context
func (_e *UploadStatusAction_Expecter) Invoke(context interface{}) *UploadStatusAction_Invoke_Call {
	return &UploadStatusAction_Invoke_Call{Call: _e.mock.On("Invoke", context)}
}

func (_c *UploadStatusAction_Invoke_Call) Run(run func(context *gin.Context)) *UploadStatusAction_Invoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *UploadStatusAction_Invoke_Call) Return() *UploadStatusAction_Invoke_Call {
	_c.Call.Return()
	return _c
}

func (_c *UploadStatusAction_Invoke_Call) RunAndReturn(run func(*gin.Context)) *UploadStatusAction_Invoke_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewUploadStatusAction interface {
	mock.TestingT
	Cleanup(func())
}

// NewUploadStatusAction creates a new instance of UploadStatusAction. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUploadStatusAction(t mockConstructorTestingTNewUploadStatusAction) *UploadStatusAction {
	mock := &UploadStatusAction{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
