// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// UploadAction is an autogenerated mock type for the UploadAction type
type UploadAction struct {
	mock.Mock
}

type UploadAction_Expecter struct {
	mock *mock.Mock
}

func (_m *UploadAction) EXPECT() *UploadAction_Expecter {
	return &UploadAction_Expecter{mock: &_m.Mock}
}

// Invoke provides a mock function with given fields: context
func (_m *UploadAction) Invoke(context *gin.Context) {
	_m.Called(context)
}

// UploadAction_Invoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Invoke'
type UploadAction_Invoke_Call struct {
	*mock.Call
}

// Invoke is a helper method to define mock.On call
//   - context *gin.Context
func (_e *UploadAction_Expecter) Invoke(context interface{}) *UploadAction_Invoke_Call {
	return &UploadAction_Invoke_Call{Call: _e.mock.On("Invoke", context)}
}

func (_c *UploadAction_Invoke_Call) Run(run func(context *gin.Context)) *UploadAction_Invoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *UploadAction_Invoke_Call) Return() *UploadAction_Invoke_Call {
	_c.Call.Return()
	return _c
}

func (_c *UploadAction_Invoke_Call) RunAndReturn(run func(*gin.Context)) *UploadAction_Invoke_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewUploadAction interface {
	mock.TestingT
	Cleanup(func())
}

// NewUploadAction creates a new instance of UploadAction. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUploadAction(t mockConstructorTestingTNewUploadAction) *UploadAction {
	mock := &UploadAction{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
