// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// AverageClusteringCoefficientAction is an autogenerated mock type for the AverageClusteringCoefficientAction type
type AverageClusteringCoefficientAction struct {
	mock.Mock
}

type AverageClusteringCoefficientAction_Expecter struct {
	mock *mock.Mock
}

func (_m *AverageClusteringCoefficientAction) EXPECT() *AverageClusteringCoefficientAction_Expecter {
	return &AverageClusteringCoefficientAction_Expecter{mock: &_m.Mock}
}

// Invoke provides a mock function with given fields: context
func (_m *AverageClusteringCoefficientAction) Invoke(context *gin.Context) {
	_m.Called(context)
}

// AverageClusteringCoefficientAction_Invoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Invoke'
type AverageClusteringCoefficientAction_Invoke_Call struct {
	*mock.Call
}

// Invoke is a helper method to define mock.On call
//   - context *gin.Context
func (_e *AverageClusteringCoefficientAction_Expecter) Invoke(context interface{}) *AverageClusteringCoefficientAction_Invoke_Call {
	return &AverageClusteringCoefficientAction_Invoke_Call{Call: _e.mock.On("Invoke", context)}
}

func (_c *AverageClusteringCoefficientAction_Invoke_Call) Run(run func(context *gin.Context)) *AverageClusteringCoefficientAction_Invoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *AverageClusteringCoefficientAction_Invoke_Call) Return() *AverageClusteringCoefficientAction_Invoke_Call {
	_c.Call.Return()
	return _c
}

func (_c *AverageClusteringCoefficientAction_Invoke_Call) RunAndReturn(run func(*gin.Context)) *AverageClusteringCoefficientAction_Invoke_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewAverageClusteringCoefficientAction interface {
	mock.TestingT
	Cleanup(func())
}

// NewAverageClusteringCoefficientAction creates a new instance of AverageClusteringCoefficientAction. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAverageClusteringCoefficientAction(t mockConstructorTestingTNewAverageClusteringCoefficientAction) *AverageClusteringCoefficientAction {
	mock := &AverageClusteringCoefficientAction{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
