// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// ConnectedAction is an autogenerated mock type for the ConnectedAction type
type ConnectedAction struct {
	mock.Mock
}

type ConnectedAction_Expecter struct {
	mock *mock.Mock
}

func (_m *ConnectedAction) EXPECT() *ConnectedAction_Expecter {
	return &ConnectedAction_Expecter{mock: &_m.Mock}
}

// Invoke provides a mock function with given fields: context
func (_m *ConnectedAction) Invoke(context *gin.Context) {
	_m.Called(context)
}

// ConnectedAction_Invoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Invoke'
type ConnectedAction_Invoke_Call struct {
	*mock.Call
}

// Invoke is a helper method to define mock.On call
//   - context *gin.Context
func (_e *ConnectedAction_Expecter) Invoke(context interface{}) *ConnectedAction_Invoke_Call {
	return &ConnectedAction_Invoke_Call{Call: _e.mock.On("Invoke", context)}
}

func (_c *ConnectedAction_Invoke_Call) Run(run func(context *gin.Context)) *ConnectedAction_Invoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *ConnectedAction_Invoke_Call) Return() *ConnectedAction_Invoke_Call {
	_c.Call.Return()
	return _c
}

func (_c *ConnectedAction_Invoke_Call) RunAndReturn(run func(*gin.Context)) *ConnectedAction_Invoke_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewConnectedAction interface {
	mock.TestingT
	Cleanup(func())
}

// NewConnectedAction creates a new instance of ConnectedAction. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewConnectedAction(t mockConstructorTestingTNewConnectedAction) *ConnectedAction {
	mock := &ConnectedAction{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
