// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// DegreeCorrelationAction is an autogenerated mock type for the DegreeCorrelationAction type
type DegreeCorrelationAction struct {
	mock.Mock
}

type DegreeCorrelationAction_Expecter struct {
	mock *mock.Mock
}

func (_m *DegreeCorrelationAction) EXPECT() *DegreeCorrelationAction_Expecter {
	return &DegreeCorrelationAction_Expecter{mock: &_m.Mock}
}

// Invoke provides a mock function with given fields: context
func (_m *DegreeCorrelationAction) Invoke(context *gin.Context) {
	_m.Called(context)
}

// DegreeCorrelationAction_Invoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Invoke'
type DegreeCorrelationAction_Invoke_Call struct {
	*mock.Call
}

// Invoke is a helper method to define mock.On call
//   - context *gin.Context
func (_e *DegreeCorrelationAction_Expecter) Invoke(context interface{}) *DegreeCorrelationAction_Invoke_Call {
	return &DegreeCorrelationAction_Invoke_Call{Call: _e.mock.On("Invoke", context)}
}

func (_c *DegreeCorrelationAction_Invoke_Call) Run(run func(context *gin.Context)) *DegreeCorrelationAction_Invoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *DegreeCorrelationAction_Invoke_Call) Return() *DegreeCorrelationAction_Invoke_Call {
	_c.Call.Return()
	return _c
}

func (_c *DegreeCorrelationAction_Invoke_Call) RunAndReturn(run func(*gin.Context)) *DegreeCorrelationAction_Invoke_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewDegreeCorrelationAction interface {
	mock.TestingT
	Cleanup(func())
}

// NewDegreeCorrelationAction creates a new instance of DegreeCorrelationAction. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDegreeCorrelationAction(t mockConstructorTestingTNewDegreeCorrelationAction) *DegreeCorrelationAction {
	mock := &DegreeCorrelationAction{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
