// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// DegreeDistributionAction is an autogenerated mock type for the DegreeDistributionAction type
type DegreeDistributionAction struct {
	mock.Mock
}

type DegreeDistributionAction_Expecter struct {
	mock *mock.Mock
}

func (_m *DegreeDistributionAction) EXPECT() *DegreeDistributionAction_Expecter {
	return &DegreeDistributionAction_Expecter{mock: &_m.Mock}
}

// Invoke provides a mock function with given fields: context
func (_m *DegreeDistributionAction) Invoke(context *gin.Context) {
	_m.Called(context)
}

// DegreeDistributionAction_Invoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Invoke'
type DegreeDistributionAction_Invoke_Call struct {
	*mock.Call
}

// Invoke is a helper method to define mock.On call
//   - context *gin.Context
func (_e *DegreeDistributionAction_Expecter) Invoke(context interface{}) *DegreeDistributionAction_Invoke_Call {
	return &DegreeDistributionAction_Invoke_Call{Call: _e.mock.On("Invoke", context)}
}

func (_c *DegreeDistributionAction_Invoke_Call) Run(run func(context *gin.Context)) *DegreeDistributionAction_Invoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *DegreeDistributionAction_Invoke_Call) Return() *DegreeDistributionAction_Invoke_Call {
	_c.Call.Return()
	return _c
}

func (_c *DegreeDistributionAction_Invoke_Call) RunAndReturn(run func(*gin.Context)) *DegreeDistributionAction_Invoke_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewDegreeDistributionAction interface {
	mock.TestingT
	Cleanup(func())
}

// NewDegreeDistributionAction creates a new instance of DegreeDistributionAction. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDegreeDistributionAction(t mockConstructorTestingTNewDegreeDistributionAction) *DegreeDistributionAction {
	mock := &DegreeDistributionAction{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
