// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// DegreeAssortativityCoefficientAction is an autogenerated mock type for the DegreeAssortativityCoefficientAction type
type DegreeAssortativityCoefficientAction struct {
	mock.Mock
}

type DegreeAssortativityCoefficientAction_Expecter struct {
	mock *mock.Mock
}

func (_m *DegreeAssortativityCoefficientAction) EXPECT() *DegreeAssortativityCoefficientAction_Expecter {
	return &DegreeAssortativityCoefficientAction_Expecter{mock: &_m.Mock}
}

// Invoke provides a mock function with given fields: context
func (_m *DegreeAssortativityCoefficientAction) Invoke(context *gin.Context) {
	_m.Called(context)
}

// DegreeAssortativityCoefficientAction_Invoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Invoke'
type DegreeAssortativityCoefficientAction_Invoke_Call struct {
	*mock.Call
}

// Invoke is a helper method to define mock.On call
//   - context *gin.Context
func (_e *DegreeAssortativityCoefficientAction_Expecter) Invoke(context interface{}) *DegreeAssortativityCoefficientAction_Invoke_Call {
	return &DegreeAssortativityCoefficientAction_Invoke_Call{Call: _e.mock.On("Invoke", context)}
}

func (_c *DegreeAssortativityCoefficientAction_Invoke_Call) Run(run func(context *gin.Context)) *DegreeAssortativityCoefficientAction_Invoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *DegreeAssortativityCoefficientAction_Invoke_Call) Return() *DegreeAssortativityCoefficientAction_Invoke_Call {
	_c.Call.Return()
	return _c
}

func (_c *DegreeAssortativityCoefficientAction_Invoke_Call) RunAndReturn(run func(*gin.Context)) *DegreeAssortativityCoefficientAction_Invoke_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewDegreeAssortativityCoefficientAction interface {
	mock.TestingT
	Cleanup(func())
}

// NewDegreeAssortativityCoefficientAction creates a new instance of DegreeAssortativityCoefficientAction. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDegreeAssortativityCoefficientAction(t mockConstructorTestingTNewDegreeAssortativityCoefficientAction) *DegreeAssortativityCoefficientAction {
	mock := &DegreeAssortativityCoefficientAction{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
