// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// DensityAction is an autogenerated mock type for the DensityAction type
type DensityAction struct {
	mock.Mock
}

type DensityAction_Expecter struct {
	mock *mock.Mock
}

func (_m *DensityAction) EXPECT() *DensityAction_Expecter {
	return &DensityAction_Expecter{mock: &_m.Mock}
}

// Invoke provides a mock function with given fields: context
func (_m *DensityAction) Invoke(context *gin.Context) {
	_m.Called(context)
}

// DensityAction_Invoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Invoke'
type DensityAction_Invoke_Call struct {
	*mock.Call
}

// Invoke is a helper method to define mock.On call
//   - context *gin.Context
func (_e *DensityAction_Expecter) Invoke(context interface{}) *DensityAction_Invoke_Call {
	return &DensityAction_Invoke_Call{Call: _e.mock.On("Invoke", context)}
}

func (_c *DensityAction_Invoke_Call) Run(run func(context *gin.Context)) *DensityAction_Invoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *DensityAction_Invoke_Call) Return() *DensityAction_Invoke_Call {
	_c.Call.Return()
	return _c
}

func (_c *DensityAction_Invoke_Call) RunAndReturn(run func(*gin.Context)) *DensityAction_Invoke_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewDensityAction interface {
	mock.TestingT
	Cleanup(func())
}

// NewDensityAction creates a new instance of DensityAction. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDensityAction(t mockConstructorTestingTNewDensityAction) *DensityAction {
	mock := &DensityAction{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
