// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// DiameterAction is an autogenerated mock type for the DiameterAction type
type DiameterAction struct {
	mock.Mock
}

type DiameterAction_Expecter struct {
	mock *mock.Mock
}

func (_m *DiameterAction) EXPECT() *DiameterAction_Expecter {
	return &DiameterAction_Expecter{mock: &_m.Mock}
}

// Invoke provides a mock function with given fields: context
func (_m *DiameterAction) Invoke(context *gin.Context) {
	_m.Called(context)
}

// DiameterAction_Invoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Invoke'
type DiameterAction_Invoke_Call struct {
	*mock.Call
}

// Invoke is a helper method to define mock.On call
//   - context *gin.Context
func (_e *DiameterAction_Expecter) Invoke(context interface{}) *DiameterAction_Invoke_Call {
	return &DiameterAction_Invoke_Call{Call: _e.mock.On("Invoke", context)}
}

func (_c *DiameterAction_Invoke_Call) Run(run func(context *gin.Context)) *DiameterAction_Invoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *DiameterAction_Invoke_Call) Return() *DiameterAction_Invoke_Call {
	_c.Call.Return()
	return _c
}

func (_c *DiameterAction_Invoke_Call) RunAndReturn(run func(*gin.Context)) *DiameterAction_Invoke_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewDiameterAction interface {
	mock.TestingT
	Cleanup(func())
}

// NewDiameterAction creates a new instance of DiameterAction. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDiameterAction(t mockConstructorTestingTNewDiameterAction) *DiameterAction {
	mock := &DiameterAction{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
