// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// FullGraphAction is an autogenerated mock type for the FullGraphAction type
type FullGraphAction struct {
	mock.Mock
}

type FullGraphAction_Expecter struct {
	mock *mock.Mock
}

func (_m *FullGraphAction) EXPECT() *FullGraphAction_Expecter {
	return &FullGraphAction_Expecter{mock: &_m.Mock}
}

// Invoke provides a mock function with given fields: context
func (_m *FullGraphAction) Invoke(context *gin.Context) {
	_m.Called(context)
}

// FullGraphAction_Invoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Invoke'
type FullGraphAction_Invoke_Call struct {
	*mock.Call
}

// Invoke is a helper method to define mock.On call
//   - context *gin.Context
func (_e *FullGraphAction_Expecter) Invoke(context interface{}) *FullGraphAction_Invoke_Call {
	return &FullGraphAction_Invoke_Call{Call: _e.mock.On("Invoke", context)}
}

func (_c *FullGraphAction_Invoke_Call) Run(run func(context *gin.Context)) *FullGraphAction_Invoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *FullGraphAction_Invoke_Call) Return() *FullGraphAction_Invoke_Call {
	_c.Call.Return()
	return _c
}

func (_c *FullGraphAction_Invoke_Call) RunAndReturn(run func(*gin.Context)) *FullGraphAction_Invoke_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewFullGraphAction interface {
	mock.TestingT
	Cleanup(func())
}

// NewFullGraphAction creates a new instance of FullGraphAction. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewFullGraphAction(t mockConstructorTestingTNewFullGraphAction) *FullGraphAction {
	mock := &FullGraphAction{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
