// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// HasCutVertexAction is an autogenerated mock type for the HasCutVertexAction type
type HasCutVertexAction struct {
	mock.Mock
}

type HasCutVertexAction_Expecter struct {
	mock *mock.Mock
}

func (_m *HasCutVertexAction) EXPECT() *HasCutVertexAction_Expecter {
	return &HasCutVertexAction_Expecter{mock: &_m.Mock}
}

// Invoke provides a mock function with given fields: context
func (_m *HasCutVertexAction) Invoke(context *gin.Context) {
	_m.Called(context)
}

// HasCutVertexAction_Invoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Invoke'
type HasCutVertexAction_Invoke_Call struct {
	*mock.Call
}

// Invoke is a helper method to define mock.On call
//   - context *gin.Context
func (_e *HasCutVertexAction_Expecter) Invoke(context interface{}) *HasCutVertexAction_Invoke_Call {
	return &HasCutVertexAction_Invoke_Call{Call: _e.mock.On("Invoke", context)}
}

func (_c *HasCutVertexAction_Invoke_Call) Run(run func(context *gin.Context)) *HasCutVertexAction_Invoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *HasCutVertexAction_Invoke_Call) Return() *HasCutVertexAction_Invoke_Call {
	_c.Call.Return()
	return _c
}

func (_c *HasCutVertexAction_Invoke_Call) RunAndReturn(run func(*gin.Context)) *HasCutVertexAction_Invoke_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewHasCutVertexAction interface {
	mock.TestingT
	Cleanup(func())
}

// NewHasCutVertexAction creates a new instance of HasCutVertexAction. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewHasCutVertexAction(t mockConstructorTestingTNewHasCutVertexAction) *HasCutVertexAction {
	mock := &HasCutVertexAction{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
