// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// HasCutEdgeAction is an autogenerated mock type for the HasCutEdgeAction type
type HasCutEdgeAction struct {
	mock.Mock
}

type HasCutEdgeAction_Expecter struct {
	mock *mock.Mock
}

func (_m *HasCutEdgeAction) EXPECT() *HasCutEdgeAction_Expecter {
	return &HasCutEdgeAction_Expecter{mock: &_m.Mock}
}

// Invoke provides a mock function with given fields: context
func (_m *HasCutEdgeAction) Invoke(context *gin.Context) {
	_m.Called(context)
}

// HasCutEdgeAction_Invoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Invoke'
type HasCutEdgeAction_Invoke_Call struct {
	*mock.Call
}

// Invoke is a helper method to define mock.On call
//   - context *gin.Context
func (_e *HasCutEdgeAction_Expecter) Invoke(context interface{}) *HasCutEdgeAction_Invoke_Call {
	return &HasCutEdgeAction_Invoke_Call{Call: _e.mock.On("Invoke", context)}
}

func (_c *HasCutEdgeAction_Invoke_Call) Run(run func(context *gin.Context)) *HasCutEdgeAction_Invoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *HasCutEdgeAction_Invoke_Call) Return() *HasCutEdgeAction_Invoke_Call {
	_c.Call.Return()
	return _c
}

func (_c *HasCutEdgeAction_Invoke_Call) RunAndReturn(run func(*gin.Context)) *HasCutEdgeAction_Invoke_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewHasCutEdgeAction interface {
	mock.TestingT
	Cleanup(func())
}

// NewHasCutEdgeAction creates a new instance of HasCutEdgeAction. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewHasCutEdgeAction(t mockConstructorTestingTNewHasCutEdgeAction) *HasCutEdgeAction {
	mock := &HasCutEdgeAction{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
