// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// QueryAction is an autogenerated mock type for the QueryAction type
type QueryAction struct {
	mock.Mock
}

type QueryAction_Expecter struct {
	mock *mock.Mock
}

func (_m *QueryAction) EXPECT() *QueryAction_Expecter {
	return &QueryAction_Expecter{mock: &_m.Mock}
}

// Invoke provides a mock function with given fields: context
func (_m *QueryAction) Invoke(context *gin.Context) {
	_m.Called(context)
}

// QueryAction_Invoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Invoke'
type QueryAction_Invoke_Call struct {
	*mock.Call
}

// Invoke is a helper method to define mock.On call
//   - context *gin.Context
func (_e *QueryAction_Expecter) Invoke(context interface{}) *QueryAction_Invoke_Call {
	return &QueryAction_Invoke_Call{Call: _e.mock.On("Invoke", context)}
}

func (_c *QueryAction_Invoke_Call) Run(run func(context *gin.Context)) *QueryAction_Invoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *QueryAction_Invoke_Call) Return() *QueryAction_Invoke_Call {
	_c.Call.Return()
	return _c
}

func (_c *QueryAction_Invoke_Call) RunAndReturn(run func(*gin.Context)) *QueryAction_Invoke_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewQueryAction interface {
	mock.TestingT
	Cleanup(func())
}

// NewQueryAction creates a new instance of QueryAction. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewQueryAction(t mockConstructorTestingTNewQueryAction) *QueryAction {
	mock := &QueryAction{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
