// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// RobustnessAction is an autogenerated mock type for the RobustnessAction type
type RobustnessAction struct {
	mock.Mock
}

type RobustnessAction_Expecter struct {
	mock *mock.Mock
}

func (_m *RobustnessAction) EXPECT() *RobustnessAction_Expecter {
	return &RobustnessAction_Expecter{mock: &_m.Mock}
}

// Invoke provides a mock function with given fields: context
func (_m *RobustnessAction) Invoke(context *gin.Context) {
	_m.Called(context)
}

// RobustnessAction_Invoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Invoke'
type RobustnessAction_Invoke_Call struct {
	*mock.Call
}

// Invoke is a helper method to define mock.On call
//   - context *gin.Context
func (_e *RobustnessAction_Expecter) Invoke(context interface{}) *RobustnessAction_Invoke_Call {
	return &RobustnessAction_Invoke_Call{Call: _e.mock.On("Invoke", context)}
}

func (_c *RobustnessAction_Invoke_Call) Run(run func(context *gin.Context)) *RobustnessAction_Invoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *RobustnessAction_Invoke_Call) Return() *RobustnessAction_Invoke_Call {
	_c.Call.Return()
	return _c
}

func (_c *RobustnessAction_Invoke_Call) RunAndReturn(run func(*gin.Context)) *RobustnessAction_Invoke_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewRobustnessAction interface {
	mock.TestingT
	Cleanup(func())
}

// NewRobustnessAction creates a new instance of RobustnessAction. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewRobustnessAction(t mockConstructorTestingTNewRobustnessAction) *RobustnessAction {
	mock := &RobustnessAction{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
