// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// Action is an autogenerated mock type for the Action type
type Action struct {
	mock.Mock
}

type Action_Expecter struct {
	mock *mock.Mock
}

func (_m *Action) EXPECT() *Action_Expecter {
	return &Action_Expecter{mock: &_m.Mock}
}

// Invoke provides a mock function with given fields: context
func (_m *Action) Invoke(context *gin.Context) {
	_m.Called(context)
}

// Action_Invoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Invoke'
type Action_Invoke_Call struct {
	*mock.Call
}

// Invoke is a helper method to define mock.On call
//   - context *gin.Context
func (_e *Action_Expecter) Invoke(context interface{}) *Action_Invoke_Call {
	return &Action_Invoke_Call{Call: _e.mock.On("Invoke", context)}
}

func (_c *Action_Invoke_Call) Run(run func(context *gin.Context)) *Action_Invoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*gin.Context))
	})
	return _c
}

func (_c *Action_Invoke_Call) Return() *Action_Invoke_Call {
	_c.Call.Return()
	return _c
}

func (_c *Action_Invoke_Call) RunAndReturn(run func(*gin.Context)) *Action_Invoke_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewAction interface {
	mock.TestingT
	Cleanup(func())
}

// NewAction creates a new instance of Action. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAction(t mockConstructorTestingTNewAction) *Action {
	mock := &Action{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
