// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	domain "graph-analyzer/api/graph-property/domain"

	mock "github.com/stretchr/testify/mock"
)

// AverageClusteringCoefficientResponder is an autogenerated mock type for the AverageClusteringCoefficientResponder type
type AverageClusteringCoefficientResponder struct {
	mock.Mock
}

type AverageClusteringCoefficientResponder_Expecter struct {
	mock *mock.Mock
}

func (_m *AverageClusteringCoefficientResponder) EXPECT() *AverageClusteringCoefficientResponder_Expecter {
	return &AverageClusteringCoefficientResponder_Expecter{mock: &_m.Mock}
}

// CreateSuccessfulResponse provides a mock function with given fields: dto
func (_m *AverageClusteringCoefficientResponder) CreateSuccessfulResponse(dto domain.AverageClusteringCoefficientDTO) {
	_m.Called(dto)
}

// AverageClusteringCoefficientResponder_CreateSuccessfulResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSuccessfulResponse'
type AverageClusteringCoefficientResponder_CreateSuccessfulResponse_Call struct {
	*mock.Call
}

// CreateSuccessfulResponse is a helper method to define mock.On call
//   - dto domain.AverageClusteringCoefficientDTO
func (_e *AverageClusteringCoefficientResponder_Expecter) CreateSuccessfulResponse(dto interface{}) *AverageClusteringCoefficientResponder_CreateSuccessfulResponse_Call {
	return &AverageClusteringCoefficientResponder_CreateSuccessfulResponse_Call{Call: _e.mock.On("CreateSuccessfulResponse", dto)}
}

func (_c *AverageClusteringCoefficientResponder_CreateSuccessfulResponse_Call) Run(run func(dto domain.AverageClusteringCoefficientDTO)) *AverageClusteringCoefficientResponder_CreateSuccessfulResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(domain.AverageClusteringCoefficientDTO))
	})
	return _c
}

func (_c *AverageClusteringCoefficientResponder_CreateSuccessfulResponse_Call) Return() *AverageClusteringCoefficientResponder_CreateSuccessfulResponse_Call {
	_c.Call.Return()
	return _c
}

func (_c *AverageClusteringCoefficientResponder_CreateSuccessfulResponse_Call) RunAndReturn(run func(domain.AverageClusteringCoefficientDTO)) *AverageClusteringCoefficientResponder_CreateSuccessfulResponse_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewAverageClusteringCoefficientResponder interface {
	mock.TestingT
	Cleanup(func())
}

// NewAverageClusteringCoefficientResponder creates a new instance of AverageClusteringCoefficientResponder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAverageClusteringCoefficientResponder(t mockConstructorTestingTNewAverageClusteringCoefficientResponder) *AverageClusteringCoefficientResponder {
	mock := &AverageClusteringCoefficientResponder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
