// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	domain "graph-analyzer/api/graph-property/domain"

	mock "github.com/stretchr/testify/mock"
)

// ConnectedResponder is an autogenerated mock type for the ConnectedResponder type
type ConnectedResponder struct {
	mock.Mock
}

type ConnectedResponder_Expecter struct {
	mock *mock.Mock
}

func (_m *ConnectedResponder) EXPECT() *ConnectedResponder_Expecter {
	return &ConnectedResponder_Expecter{mock: &_m.Mock}
}

// CreateSuccessfulResponse provides a mock function with given fields: dto
func (_m *ConnectedResponder) CreateSuccessfulResponse(dto domain.ConnectedDTO) {
	_m.Called(dto)
}

// ConnectedResponder_CreateSuccessfulResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSuccessfulResponse'
type ConnectedResponder_CreateSuccessfulResponse_Call struct {
	*mock.Call
}

// CreateSuccessfulResponse is a helper method to define mock.On call
//   - dto domain.ConnectedDTO
func (_e *ConnectedResponder_Expecter) CreateSuccessfulResponse(dto interface{}) *ConnectedResponder_CreateSuccessfulResponse_Call {
	return &ConnectedResponder_CreateSuccessfulResponse_Call{Call: _e.mock.On("CreateSuccessfulResponse", dto)}
}

func (_c *ConnectedResponder_CreateSuccessfulResponse_Call) Run(run func(dto domain.ConnectedDTO)) *ConnectedResponder_CreateSuccessfulResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(domain.ConnectedDTO))
	})
	return _c
}

func (_c *ConnectedResponder_CreateSuccessfulResponse_Call) Return() *ConnectedResponder_CreateSuccessfulResponse_Call {
	_c.Call.Return()
	return _c
}

func (_c *ConnectedResponder_CreateSuccessfulResponse_Call) RunAndReturn(run func(domain.ConnectedDTO)) *ConnectedResponder_CreateSuccessfulResponse_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewConnectedResponder interface {
	mock.TestingT
	Cleanup(func())
}

// NewConnectedResponder creates a new instance of ConnectedResponder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewConnectedResponder(t mockConstructorTestingTNewConnectedResponder) *ConnectedResponder {
	mock := &ConnectedResponder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
