// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	domain "graph-analyzer/api/graph-property/domain"

	mock "github.com/stretchr/testify/mock"
)

// DegreeCorrelationResponder is an autogenerated mock type for the DegreeCorrelationResponder type
type DegreeCorrelationResponder struct {
	mock.Mock
}

type DegreeCorrelationResponder_Expecter struct {
	mock *mock.Mock
}

func (_m *DegreeCorrelationResponder) EXPECT() *DegreeCorrelationResponder_Expecter {
	return &DegreeCorrelationResponder_Expecter{mock: &_m.Mock}
}

// CreateSuccessfulResponse provides a mock function with given fields: dto
func (_m *DegreeCorrelationResponder) CreateSuccessfulResponse(dto domain.DegreeCorrelationDTO) {
	_m.Called(dto)
}

// DegreeCorrelationResponder_CreateSuccessfulResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSuccessfulResponse'
type DegreeCorrelationResponder_CreateSuccessfulResponse_Call struct {
	*mock.Call
}

// CreateSuccessfulResponse is a helper method to define mock.On call
//   - dto domain.DegreeCorrelationDTO
func (_e *DegreeCorrelationResponder_Expecter) CreateSuccessfulResponse(dto interface{}) *DegreeCorrelationResponder_CreateSuccessfulResponse_Call {
	return &DegreeCorrelationResponder_CreateSuccessfulResponse_Call{Call: _e.mock.On("CreateSuccessfulResponse", dto)}
}

func (_c *DegreeCorrelationResponder_CreateSuccessfulResponse_Call) Run(run func(dto domain.DegreeCorrelationDTO)) *DegreeCorrelationResponder_CreateSuccessfulResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(domain.DegreeCorrelationDTO))
	})
	return _c
}

func (_c *DegreeCorrelationResponder_CreateSuccessfulResponse_Call) Return() *DegreeCorrelationResponder_CreateSuccessfulResponse_Call {
	_c.Call.Return()
	return _c
}

func (_c *DegreeCorrelationResponder_CreateSuccessfulResponse_Call) RunAndReturn(run func(domain.DegreeCorrelationDTO)) *DegreeCorrelationResponder_CreateSuccessfulResponse_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewDegreeCorrelationResponder interface {
	mock.TestingT
	Cleanup(func())
}

// NewDegreeCorrelationResponder creates a new instance of DegreeCorrelationResponder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDegreeCorrelationResponder(t mockConstructorTestingTNewDegreeCorrelationResponder) *DegreeCorrelationResponder {
	mock := &DegreeCorrelationResponder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
