// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	domain "graph-analyzer/api/graph-property/domain"

	mock "github.com/stretchr/testify/mock"
)

// DegreeAssortativityCoefficientResponder is an autogenerated mock type for the DegreeAssortativityCoefficientResponder type
type DegreeAssortativityCoefficientResponder struct {
	mock.Mock
}

type DegreeAssortativityCoefficientResponder_Expecter struct {
	mock *mock.Mock
}

func (_m *DegreeAssortativityCoefficientResponder) EXPECT() *DegreeAssortativityCoefficientResponder_Expecter {
	return &DegreeAssortativityCoefficientResponder_Expecter{mock: &_m.Mock}
}

// CreateSuccessfulResponse provides a mock function with given fields: dto
func (_m *DegreeAssortativityCoefficientResponder) CreateSuccessfulResponse(dto domain.DegreeAssortativityCoefficientDTO) {
	_m.Called(dto)
}

// DegreeAssortativityCoefficientResponder_CreateSuccessfulResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSuccessfulResponse'
type DegreeAssortativityCoefficientResponder_CreateSuccessfulResponse_Call struct {
	*mock.Call
}

// CreateSuccessfulResponse is a helper method to define mock.On call
//   - dto domain.DegreeAssortativityCoefficientDTO
func (_e *DegreeAssortativityCoefficientResponder_Expecter) CreateSuccessfulResponse(dto interface{}) *DegreeAssortativityCoefficientResponder_CreateSuccessfulResponse_Call {
	return &DegreeAssortativityCoefficientResponder_CreateSuccessfulResponse_Call{Call: _e.mock.On("CreateSuccessfulResponse", dto)}
}

func (_c *DegreeAssortativityCoefficientResponder_CreateSuccessfulResponse_Call) Run(run func(dto domain.DegreeAssortativityCoefficientDTO)) *DegreeAssortativityCoefficientResponder_CreateSuccessfulResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(domain.DegreeAssortativityCoefficientDTO))
	})
	return _c
}

func (_c *DegreeAssortativityCoefficientResponder_CreateSuccessfulResponse_Call) Return() *DegreeAssortativityCoefficientResponder_CreateSuccessfulResponse_Call {
	_c.Call.Return()
	return _c
}

func (_c *DegreeAssortativityCoefficientResponder_CreateSuccessfulResponse_Call) RunAndReturn(run func(domain.DegreeAssortativityCoefficientDTO)) *DegreeAssortativityCoefficientResponder_CreateSuccessfulResponse_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewDegreeAssortativityCoefficientResponder interface {
	mock.TestingT
	Cleanup(func())
}

// NewDegreeAssortativityCoefficientResponder creates a new instance of DegreeAssortativityCoefficientResponder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDegreeAssortativityCoefficientResponder(t mockConstructorTestingTNewDegreeAssortativityCoefficientResponder) *DegreeAssortativityCoefficientResponder {
	mock := &DegreeAssortativityCoefficientResponder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
