// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	domain "graph-analyzer/api/graph-property/domain"

	mock "github.com/stretchr/testify/mock"
)

// DensityResponder is an autogenerated mock type for the DensityResponder type
type DensityResponder struct {
	mock.Mock
}

type DensityResponder_Expecter struct {
	mock *mock.Mock
}

func (_m *DensityResponder) EXPECT() *DensityResponder_Expecter {
	return &DensityResponder_Expecter{mock: &_m.Mock}
}

// CreateSuccessfulResponse provides a mock function with given fields: dto
func (_m *DensityResponder) CreateSuccessfulResponse(dto domain.DensityDTO) {
	_m.Called(dto)
}

// DensityResponder_CreateSuccessfulResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSuccessfulResponse'
type DensityResponder_CreateSuccessfulResponse_Call struct {
	*mock.Call
}

// CreateSuccessfulResponse is a helper method to define mock.On call
//   - dto domain.DensityDTO
func (_e *DensityResponder_Expecter) CreateSuccessfulResponse(dto interface{}) *DensityResponder_CreateSuccessfulResponse_Call {
	return &DensityResponder_CreateSuccessfulResponse_Call{Call: _e.mock.On("CreateSuccessfulResponse", dto)}
}

func (_c *DensityResponder_CreateSuccessfulResponse_Call) Run(run func(dto domain.DensityDTO)) *DensityResponder_CreateSuccessfulResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(domain.DensityDTO))
	})
	return _c
}

func (_c *DensityResponder_CreateSuccessfulResponse_Call) Return() *DensityResponder_CreateSuccessfulResponse_Call {
	_c.Call.Return()
	return _c
}

func (_c *DensityResponder_CreateSuccessfulResponse_Call) RunAndReturn(run func(domain.DensityDTO)) *DensityResponder_CreateSuccessfulResponse_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewDensityResponder interface {
	mock.TestingT
	Cleanup(func())
}

// NewDensityResponder creates a new instance of DensityResponder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDensityResponder(t mockConstructorTestingTNewDensityResponder) *DensityResponder {
	mock := &DensityResponder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
