// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	domain "graph-analyzer/api/graph-property/domain"

	mock "github.com/stretchr/testify/mock"
)

// DiameterResponder is an autogenerated mock type for the DiameterResponder type
type DiameterResponder struct {
	mock.Mock
}

type DiameterResponder_Expecter struct {
	mock *mock.Mock
}

func (_m *DiameterResponder) EXPECT() *DiameterResponder_Expecter {
	return &DiameterResponder_Expecter{mock: &_m.Mock}
}

// CreateSuccessfulResponse provides a mock function with given fields: dto
func (_m *DiameterResponder) CreateSuccessfulResponse(dto domain.DiameterDTO) {
	_m.Called(dto)
}

// DiameterResponder_CreateSuccessfulResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSuccessfulResponse'
type DiameterResponder_CreateSuccessfulResponse_Call struct {
	*mock.Call
}

// CreateSuccessfulResponse is a helper method to define mock.On call
//   - dto domain.DiameterDTO
func (_e *DiameterResponder_Expecter) CreateSuccessfulResponse(dto interface{}) *DiameterResponder_CreateSuccessfulResponse_Call {
	return &DiameterResponder_CreateSuccessfulResponse_Call{Call: _e.mock.On("CreateSuccessfulResponse", dto)}
}

func (_c *DiameterResponder_CreateSuccessfulResponse_Call) Run(run func(dto domain.DiameterDTO)) *DiameterResponder_CreateSuccessfulResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(domain.DiameterDTO))
	})
	return _c
}

func (_c *DiameterResponder_CreateSuccessfulResponse_Call) Return() *DiameterResponder_CreateSuccessfulResponse_Call {
	_c.Call.Return()
	return _c
}

func (_c *DiameterResponder_CreateSuccessfulResponse_Call) RunAndReturn(run func(domain.DiameterDTO)) *DiameterResponder_CreateSuccessfulResponse_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewDiameterResponder interface {
	mock.TestingT
	Cleanup(func())
}

// NewDiameterResponder creates a new instance of DiameterResponder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDiameterResponder(t mockConstructorTestingTNewDiameterResponder) *DiameterResponder {
	mock := &DiameterResponder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
