// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	domain "graph-analyzer/api/graph-property/domain"

	mock "github.com/stretchr/testify/mock"
)

// FullGraphResponder is an autogenerated mock type for the FullGraphResponder type
type FullGraphResponder struct {
	mock.Mock
}

type FullGraphResponder_Expecter struct {
	mock *mock.Mock
}

func (_m *FullGraphResponder) EXPECT() *FullGraphResponder_Expecter {
	return &FullGraphResponder_Expecter{mock: &_m.Mock}
}

// CreateSuccessfulResponse provides a mock function with given fields: dto
func (_m *FullGraphResponder) CreateSuccessfulResponse(dto domain.FullGraphDTO) {
	_m.Called(dto)
}

// FullGraphResponder_CreateSuccessfulResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSuccessfulResponse'
type FullGraphResponder_CreateSuccessfulResponse_Call struct {
	*mock.Call
}

// CreateSuccessfulResponse is a helper method to define mock.On call
//   - dto domain.FullGraphDTO
func (_e *FullGraphResponder_Expecter) CreateSuccessfulResponse(dto interface{}) *FullGraphResponder_CreateSuccessfulResponse_Call {
	return &FullGraphResponder_CreateSuccessfulResponse_Call{Call: _e.mock.On("CreateSuccessfulResponse", dto)}
}

func (_c *FullGraphResponder_CreateSuccessfulResponse_Call) Run(run func(dto domain.FullGraphDTO)) *FullGraphResponder_CreateSuccessfulResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(domain.FullGraphDTO))
	})
	return _c
}

func (_c *FullGraphResponder_CreateSuccessfulResponse_Call) Return() *FullGraphResponder_CreateSuccessfulResponse_Call {
	_c.Call.Return()
	return _c
}

func (_c *FullGraphResponder_CreateSuccessfulResponse_Call) RunAndReturn(run func(domain.FullGraphDTO)) *FullGraphResponder_CreateSuccessfulResponse_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewFullGraphResponder interface {
	mock.TestingT
	Cleanup(func())
}

// NewFullGraphResponder creates a new instance of FullGraphResponder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewFullGraphResponder(t mockConstructorTestingTNewFullGraphResponder) *FullGraphResponder {
	mock := &FullGraphResponder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
