// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	domain "graph-analyzer/api/graph-property/domain"

	mock "github.com/stretchr/testify/mock"
)

// HasCutVertexResponder is an autogenerated mock type for the HasCutVertexResponder type
type HasCutVertexResponder struct {
	mock.Mock
}

type HasCutVertexResponder_Expecter struct {
	mock *mock.Mock
}

func (_m *HasCutVertexResponder) EXPECT() *HasCutVertexResponder_Expecter {
	return &HasCutVertexResponder_Expecter{mock: &_m.Mock}
}

// CreateSuccessfulResponse provides a mock function with given fields: dto
func (_m *HasCutVertexResponder) CreateSuccessfulResponse(dto domain.HasCutVertexDTO) {
	_m.Called(dto)
}

// HasCutVertexResponder_CreateSuccessfulResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSuccessfulResponse'
type HasCutVertexResponder_CreateSuccessfulResponse_Call struct {
	*mock.Call
}

// CreateSuccessfulResponse is a helper method to define mock.On call
//   - dto domain.HasCutVertexDTO
func (_e *HasCutVertexResponder_Expecter) CreateSuccessfulResponse(dto interface{}) *HasCutVertexResponder_CreateSuccessfulResponse_Call {
	return &HasCutVertexResponder_CreateSuccessfulResponse_Call{Call: _e.mock.On("CreateSuccessfulResponse", dto)}
}

func (_c *HasCutVertexResponder_CreateSuccessfulResponse_Call) Run(run func(dto domain.HasCutVertexDTO)) *HasCutVertexResponder_CreateSuccessfulResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(domain.HasCutVertexDTO))
	})
	return _c
}

func (_c *HasCutVertexResponder_CreateSuccessfulResponse_Call) Return() *HasCutVertexResponder_CreateSuccessfulResponse_Call {
	_c.Call.Return()
	return _c
}

func (_c *HasCutVertexResponder_CreateSuccessfulResponse_Call) RunAndReturn(run func(domain.HasCutVertexDTO)) *HasCutVertexResponder_CreateSuccessfulResponse_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewHasCutVertexResponder interface {
	mock.TestingT
	Cleanup(func())
}

// NewHasCutVertexResponder creates a new instance of HasCutVertexResponder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewHasCutVertexResponder(t mockConstructorTestingTNewHasCutVertexResponder) *HasCutVertexResponder {
	mock := &HasCutVertexResponder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
