// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// LivenessResponder is an autogenerated mock type for the LivenessResponder type
type LivenessResponder struct {
	mock.Mock
}

type LivenessResponder_Expecter struct {
	mock *mock.Mock
}

func (_m *LivenessResponder) EXPECT() *LivenessResponder_Expecter {
	return &LivenessResponder_Expecter{mock: &_m.Mock}
}

// CreateSuccessfulResponse provides a mock function with given fields:
func (_m *LivenessResponder) CreateSuccessfulResponse() {
	_m.Called()
}

// LivenessResponder_CreateSuccessfulResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSuccessfulResponse'
type LivenessResponder_CreateSuccessfulResponse_Call struct {
	*mock.Call
}

// CreateSuccessfulResponse is a helper method to define mock.On call
func (_e *LivenessResponder_Expecter) CreateSuccessfulResponse() *LivenessResponder_CreateSuccessfulResponse_Call {
	return &LivenessResponder_CreateSuccessfulResponse_Call{Call: _e.mock.On("CreateSuccessfulResponse")}
}

func (_c *LivenessResponder_CreateSuccessfulResponse_Call) Run(run func()) *LivenessResponder_CreateSuccessfulResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *LivenessResponder_CreateSuccessfulResponse_Call) Return() *LivenessResponder_CreateSuccessfulResponse_Call {
	_c.Call.Return()
	return _c
}

func (_c *LivenessResponder_CreateSuccessfulResponse_Call) RunAndReturn(run func()) *LivenessResponder_CreateSuccessfulResponse_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewLivenessResponder interface {
	mock.TestingT
	Cleanup(func())
}

// NewLivenessResponder creates a new instance of LivenessResponder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewLivenessResponder(t mockConstructorTestingTNewLivenessResponder) *LivenessResponder {
	mock := &LivenessResponder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
