// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	domain "graph-analyzer/api/graph-property/domain"

	mock "github.com/stretchr/testify/mock"
)

// AverageClusteringCoefficientService is an autogenerated mock type for the AverageClusteringCoefficientService type
type AverageClusteringCoefficientService struct {
	mock.Mock
}

type AverageClusteringCoefficientService_Expecter struct {
	mock *mock.Mock
}

func (_m *AverageClusteringCoefficientService) EXPECT() *AverageClusteringCoefficientService_Expecter {
	return &AverageClusteringCoefficientService_Expecter{mock: &_m.Mock}
}

// Invoke provides a mock function with given fields:
func (_m *AverageClusteringCoefficientService) Invoke() domain.AverageClusteringCoefficientDTO {
	ret := _m.Called()

	var r0 domain.AverageClusteringCoefficientDTO
	if rf, ok := ret.Get(0).(func() domain.AverageClusteringCoefficientDTO); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(domain.AverageClusteringCoefficientDTO)
	}

	return r0
}

// AverageClusteringCoefficientService_Invoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Invoke'
type AverageClusteringCoefficientService_Invoke_Call struct {
	*mock.Call
}

// Invoke is a helper method to define mock.On call
func (_e *AverageClusteringCoefficientService_Expecter) Invoke() *AverageClusteringCoefficientService_Invoke_Call {
	return &AverageClusteringCoefficientService_Invoke_Call{Call: _e.mock.On("Invoke")}
}

func (_c *AverageClusteringCoefficientService_Invoke_Call) Run(run func()) *AverageClusteringCoefficientService_Invoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *AverageClusteringCoefficientService_Invoke_Call) Return(_a0 domain.AverageClusteringCoefficientDTO) *AverageClusteringCoefficientService_Invoke_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *AverageClusteringCoefficientService_Invoke_Call) RunAndReturn(run func() domain.AverageClusteringCoefficientDTO) *AverageClusteringCoefficientService_Invoke_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewAverageClusteringCoefficientService interface {
	mock.TestingT
	Cleanup(func())
}

// NewAverageClusteringCoefficientService creates a new instance of AverageClusteringCoefficientService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewAverageClusteringCoefficientService(t mockConstructorTestingTNewAverageClusteringCoefficientService) *AverageClusteringCoefficientService {
	mock := &AverageClusteringCoefficientService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
