// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	domain "graph-analyzer/api/graph-property/domain"

	mock "github.com/stretchr/testify/mock"
)

// DegreeCorrelationService is an autogenerated mock type for the DegreeCorrelationService type
type DegreeCorrelationService struct {
	mock.Mock
}

type DegreeCorrelationService_Expecter struct {
	mock *mock.Mock
}

func (_m *DegreeCorrelationService) EXPECT() *DegreeCorrelationService_Expecter {
	return &DegreeCorrelationService_Expecter{mock: &_m.Mock}
}

// Invoke provides a mock function with given fields:
func (_m *DegreeCorrelationService) Invoke() domain.DegreeCorrelationDTO {
	ret := _m.Called()

	var r0 domain.DegreeCorrelationDTO
	if rf, ok := ret.Get(0).(func() domain.DegreeCorrelationDTO); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(domain.DegreeCorrelationDTO)
	}

	return r0
}

// DegreeCorrelationService_Invoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Invoke'
type DegreeCorrelationService_Invoke_Call struct {
	*mock.Call
}

// Invoke is a helper method to define mock.On call
func (_e *DegreeCorrelationService_Expecter) Invoke() *DegreeCorrelationService_Invoke_Call {
	return &DegreeCorrelationService_Invoke_Call{Call: _e.mock.On("Invoke")}
}

func (_c *DegreeCorrelationService_Invoke_Call) Run(run func()) *DegreeCorrelationService_Invoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DegreeCorrelationService_Invoke_Call) Return(_a0 domain.DegreeCorrelationDTO) *DegreeCorrelationService_Invoke_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DegreeCorrelationService_Invoke_Call) RunAndReturn(run func() domain.DegreeCorrelationDTO) *DegreeCorrelationService_Invoke_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewDegreeCorrelationService interface {
	mock.TestingT
	Cleanup(func())
}

// NewDegreeCorrelationService creates a new instance of DegreeCorrelationService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDegreeCorrelationService(t mockConstructorTestingTNewDegreeCorrelationService) *DegreeCorrelationService {
	mock := &DegreeCorrelationService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
