// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	domain "graph-analyzer/api/graph-property/domain"

	mock "github.com/stretchr/testify/mock"
)

// DegreeAssortativityCoefficientService is an autogenerated mock type for the DegreeAssortativityCoefficientService type
type DegreeAssortativityCoefficientService struct {
	mock.Mock
}

type DegreeAssortativityCoefficientService_Expecter struct {
	mock *mock.Mock
}

func (_m *DegreeAssortativityCoefficientService) EXPECT() *DegreeAssortativityCoefficientService_Expecter {
	return &DegreeAssortativityCoefficientService_Expecter{mock: &_m.Mock}
}

// Invoke provides a mock function with given fields:
func (_m *DegreeAssortativityCoefficientService) Invoke() domain.DegreeAssortativityCoefficientDTO {
	ret := _m.Called()

	var r0 domain.DegreeAssortativityCoefficientDTO
	if rf, ok := ret.Get(0).(func() domain.DegreeAssortativityCoefficientDTO); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(domain.DegreeAssortativityCoefficientDTO)
	}

	return r0
}

// DegreeAssortativityCoefficientService_Invoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Invoke'
type DegreeAssortativityCoefficientService_Invoke_Call struct {
	*mock.Call
}

// Invoke is a helper method to define mock.On call
func (_e *DegreeAssortativityCoefficientService_Expecter) Invoke() *DegreeAssortativityCoefficientService_Invoke_Call {
	return &DegreeAssortativityCoefficientService_Invoke_Call{Call: _e.mock.On("Invoke")}
}

func (_c *DegreeAssortativityCoefficientService_Invoke_Call) Run(run func()) *DegreeAssortativityCoefficientService_Invoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *DegreeAssortativityCoefficientService_Invoke_Call) Return(_a0 domain.DegreeAssortativityCoefficientDTO) *DegreeAssortativityCoefficientService_Invoke_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DegreeAssortativityCoefficientService_Invoke_Call) RunAndReturn(run func() domain.DegreeAssortativityCoefficientDTO) *DegreeAssortativityCoefficientService_Invoke_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewDegreeAssortativityCoefficientService interface {
	mock.TestingT
	Cleanup(func())
}

// NewDegreeAssortativityCoefficientService creates a new instance of DegreeAssortativityCoefficientService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDegreeAssortativityCoefficientService(t mockConstructorTestingTNewDegreeAssortativityCoefficientService) *DegreeAssortativityCoefficientService {
	mock := &DegreeAssortativityCoefficientService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
