// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	domain "graph-analyzer/api/upload/domain"

	mock "github.com/stretchr/testify/mock"
)

// UploadStatusResponder is an autogenerated mock type for the UploadStatusResponder type
type UploadStatusResponder struct {
	mock.Mock
}

type UploadStatusResponder_Expecter struct {
	mock *mock.Mock
}

func (_m *UploadStatusResponder) EXPECT() *UploadStatusResponder_Expecter {
	return &UploadStatusResponder_Expecter{mock: &_m.Mock}
}

// CreateSuccessfulResponse provides a mock function with given fields: dto
func (_m *UploadStatusResponder) CreateSuccessfulResponse(dto domain.UploadStatusDTO) {
	_m.Called(dto)
}

// UploadStatusResponder_CreateSuccessfulResponse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSuccessfulResponse'
type UploadStatusResponder_CreateSuccessfulResponse_Call struct {
	*mock.Call
}

// CreateSuccessfulResponse is a helper method to define mock.On call
//   - dto domain.UploadStatusDTO
func (_e *UploadStatusResponder_Expecter) CreateSuccessfulResponse(dto interface{}) *UploadStatusResponder_CreateSuccessfulResponse_Call {
	return &UploadStatusResponder_CreateSuccessfulResponse_Call{Call: _e.mock.On("CreateSuccessfulResponse", dto)}
}

func (_c *UploadStatusResponder_CreateSuccessfulResponse_Call) Run(run func(dto domain.UploadStatusDTO)) *UploadStatusResponder_CreateSuccessfulResponse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(domain.UploadStatusDTO))
	})
	return _c
}

func (_c *UploadStatusResponder_CreateSuccessfulResponse_Call) Return() *UploadStatusResponder_CreateSuccessfulResponse_Call {
	_c.Call.Return()
	return _c
}

func (_c *UploadStatusResponder_CreateSuccessfulResponse_Call) RunAndReturn(run func(domain.UploadStatusDTO)) *UploadStatusResponder_CreateSuccessfulResponse_Call {
	_c.Call.Return(run)
	return _c
}

type mockConstructorTestingTNewUploadStatusResponder interface {
	mock.TestingT
	Cleanup(func())
}

// NewUploadStatusResponder creates a new instance of UploadStatusResponder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewUploadStatusResponder(t mockConstructorTestingTNewUploadStatusResponder) *UploadStatusResponder {
	mock := &UploadStatusResponder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
